feat: Set many land update operator
decentraland/rentals-contract pull request #39
Opened 2022-08-07 15:39 UTC by fzavalia

2022-08-08 19:17 UTC, nachomazzara commented on contracts/Rentals.sol
> +    /// @notice Set the operator of various individual LANDs inside an Estate
```suggestion
    /// @notice Set the operator of LANDs inside an Estate
```

2022-08-08 19:24 UTC, nachomazzara commented on contracts/Rentals.sol
> +    /// LAND update operators set previously through the Estate contract will remain.
Maybe something like ```suggestion
    /// LAND update operators can be set to assign granular permissions. LAND update operators will remain if they are inside an Estate when it is transferred. They are only cleared once the LAND is transferred. 
```

2022-08-08 19:26 UTC, nachomazzara requested changes
Just left a few comments!

2022-08-09 00:00 UTC, fzavalia commented on contracts/Rentals.sol
> +        uint256[] memory _landTokenIds,
Good idea, pushed the solution.

2022-08-09 00:01 UTC, fzavalia commented
@nachomazzara Should we emit an event when this new method is called?
I think it is unnecessary but we are doing it for the other setUpdateOperator function.
Maybe we should remove the other event.

2022-08-10 12:29 UTC, nachomazzara commented
> @nachomazzara Should we emit an event when this new method is called? I think it is unnecessary but we are doing it for the other setUpdateOperator function. Maybe we should remove the other event.

We can remove them yes. We can set up alarms and track operator changes by looking through the tx

2022-08-10 18:28 UTC, fzavalia commented
> > @nachomazzara Should we emit an event when this new method is called? I think it is unnecessary but we are doing it for the other setUpdateOperator function. Maybe we should remove the other event.
> 
> We can remove them yes. We can set up alarms and track operator changes by looking through the tx

Removed the event and added tests to check that the LAND contract is emitting them instead

2022-08-10 18:31 UTC, nachomazzara approved these changes

2022-08-10 18:38 UTC, nachomazzara approved these changes

2022-08-10 18:41 UTC, merged